var stat_names = ["crazed", "slimy", "hairy", "spikey", "scaly", "smelly", "existential"];

var monster_data = {
            eyes: [
                    {
                      name: "RedEye",
                      size: {x: 16, y:16},
                      desc: "The eyes that have seen hell",
                      cost: 10,
                      img: "eyes/RedEye.png",
                      stats: {
                        crazed: 30,
                        slimy: 10,
                        hairy: 5,
                        spikey: 10,
                        scaly: 10,
                        smelly: 5,
                        existential: 0,
                      },
                    },
                    { name: "Reptile Eyes",
                      size: {x: 16, y:16},
                      cost: 15,
                      desc: "Very snake-like",
                      img: "eyes/ReptileEyes.png",
                      stats: {
                        crazed: 20,
                        slimy: 20,
                        hairy: 0,
                        spikey: 5,
                        scaly: 20,
                        smelly: 5,
                        existential: 0,
                      },
                    },
                    { name: "Void Eyes",
                      cost: 12,
                      size: {x: 16, y:16},
                      desc: "Stare into the endless void",
                      img: "eyes/VoidEye.png",
                      stats: {
                        crazed: 0,
                        slimy: 0,
                        hairy: 0,
                        spikey: 0,
                        scaly: 0,
                        smelly: 0,
                        existential: 100,
                      },
                    },
                  ],
    
            mouths: [
                      {
                        name: "Smiling Mouth",
                        desc: "Demonic laughter...",
                        size: {x:32, y:32},
                        cost: 25,
                        img: "mouths/Smiling_Mouth.png",
                        stats: {
                          crazed: 50,
                          slimy: 3,
                          hairy: 2,
                          spikey: 10,
                          scaly: 5,
                          smelly: 5,
                          existential: 0,
                        },
                      },
                      { name: "Spinning Mouth",
                        desc: "The blender of souls",
                        size: {x:32, y:32},
                        cost: 75,
                        img: "mouths/Spinning_Mouth.png",
                        stats: {
                          crazed: 100,
                          slimy: 0,
                          hairy: 0,
                          spikey: 100,
                          scaly: 0,
                          smelly: 0,
                          existential: 10,
                        },
                      },
                      { name: "Void Mouth", 
                        size: {x:32, y:32},
                        desc: "Fall into the void...",
                        img: "mouths/Void_Mouth.png",
                        cost: 50,
                        stats: {
                          crazed: 0,
                          slimy: 0,
                          hairy: 0,
                          spikey: 0,
                          scaly: 0,
                          smelly: 0,
                          existential: 50,
                        },
                      },
                    ],
            legs: [
                    {
                      name: "Hairy Leg",
                      desc: "Hairy as a hobbit",
                      size: {x:64, y:64},
                      cost: 15,
                      img: "limbs/Green-leg.png",
                      stats: {
                        crazed: 10,
                        slimy: 0,
                        hairy: 50,
                        spikey: 0,
                        scaly: 0,
                        smelly: 15,
                        existential: 0,
                      },
                    },
                  ],
          };
        
